-- Add summary column to sessions table
ALTER TABLE sessions ADD COLUMN summary TEXT;

-- Add comment to document the column
COMMENT ON COLUMN sessions.summary IS 'Automatic summary of the session transcript generated by GPT'; 